### ISSUE TITLE
kafka dataframe to parquet writer

### ISSUE THREAD

**Issue by satishpalli** [sahabpardaz/kafka-parquet-writer#5]
Hi

i want to process my dataframes to parquet file in hdfs. but due to multiple threads(files) at a time writing it into same partition id. errors are getting. does kafka que one by one take the multi threaded files and writes the dataframe one by one as parquet file into that partition?

does this api useful for my usecase?

**Comment by ArminF1996** [comment]
It's hard to understand what you're trying to say. Can you please explain exactly what you're trying to do?

**Comment by satishpalli** [comment]
multiple csv files(dataframes) at a time i was unable to write in same partition as a parquet format .

now i was able to write using union of dataframes and write at a time.

Thanks for your reply.

**Comment by ArminF1996** [comment]
I'm not sure what you're trying to say. But if I'm right, you have multiple csv files which should be written to several parquet files. If that is the case, our project does not help you. You will have to write your own code. You can get ideas by reading our code however.
